version: '2'
services:
  tracker:
    build:
      context: .
      dockerfile: Dockerfile
    ports: 
      - 8000:80
      - 24231:24231
    volumes:
      - ./nginx/nginx.conf:/opt/nginx/conf/nginx.conf
      - ./fluentd/config/fluentd.conf:/etc/fluent/fluentd.conf
    environment:
      KAFKA_BROKERS: kafka:9092
    depends_on:
      - kafka
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - 2181:2181
  kafka:
    image: wurstmeister/kafka
    ports:
      - 9092:9092
      - 29092:29092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

      KAFKA_LISTENERS: INTERNAL://kafka:9092,EXTERNAL://localhost:29092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,EXTERNAL://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on: 
      - zookeeper
